# Generated by Django 3.1.1 on 2020-11-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
    ]
