# Generated by Django 3.1.1 on 2020-11-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='pub_date',
            new_name='sent_date',
        ),
    ]
