# Generated by Django 3.1.1 on 2020-11-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_idea_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
