# Generated by Django 3.1.1 on 2020-11-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PollUser',
        ),
    ]
